-- Up Migration

-- Enables a document to reference both its request and applicant.
ALTER TABLE resident_unit_requests
    ADD CONSTRAINT resident_requests_applicant_identity_unique
    UNIQUE (id, society_id, user_id);

CREATE TABLE resident_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    society_id UUID NOT NULL REFERENCES societies(id),
    uploaded_by UUID NOT NULL REFERENCES users(id),

    kind TEXT NOT NULL
        CHECK (kind IN ('identity', 'rental_agreement')),

    request_id UUID,
    subject_user_id UUID,
    tenancy_id UUID,
    agreement_version INTEGER,

    original_filename TEXT NOT NULL
        CHECK (char_length(btrim(original_filename)) BETWEEN 1 AND 255),

    storage_bucket TEXT NOT NULL
        CHECK (char_length(btrim(storage_bucket)) BETWEEN 1 AND 255),

    -- Generated by the backend. Never use the original filename as a key.
    storage_key TEXT NOT NULL
        CHECK (char_length(btrim(storage_key)) BETWEEN 1 AND 1024),

    declared_content_type TEXT NOT NULL
        CHECK (declared_content_type IN (
            'application/pdf', 'image/jpeg', 'image/png'
        )),

    declared_size_bytes BIGINT NOT NULL
        CHECK (declared_size_bytes BETWEEN 1 AND 10485760),

    verified_content_type TEXT
        CHECK (verified_content_type IN (
            'application/pdf', 'image/jpeg', 'image/png'
        )),

    verified_size_bytes BIGINT
        CHECK (verified_size_bytes BETWEEN 1 AND 10485760),

    sha256 TEXT CHECK (sha256 ~ '^[0-9a-f]{64}$'),

    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'ready', 'rejected', 'deleted')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    verified_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    failure_reason TEXT
        CHECK (
            failure_reason IS NULL
            OR char_length(btrim(failure_reason)) BETWEEN 1 AND 1000
        ),

    CONSTRAINT resident_documents_storage_unique
        UNIQUE (storage_bucket, storage_key),

    CONSTRAINT resident_documents_id_society_unique
        UNIQUE (id, society_id),

    CONSTRAINT resident_documents_agreement_identity_unique
        UNIQUE (id, society_id, tenancy_id),

    CONSTRAINT resident_documents_request_applicant_fk
        FOREIGN KEY (request_id, society_id, subject_user_id)
        REFERENCES resident_unit_requests(id, society_id, user_id),

    CONSTRAINT resident_documents_tenancy_fk
        FOREIGN KEY (tenancy_id, society_id)
        REFERENCES resident_tenancies(id, society_id),

    CONSTRAINT resident_documents_purpose CHECK (
        (
            kind = 'identity'
            AND request_id IS NOT NULL
            AND subject_user_id IS NOT NULL
            AND uploaded_by = subject_user_id
            AND tenancy_id IS NULL
            AND agreement_version IS NULL
        )
        OR (
            kind = 'rental_agreement'
            AND request_id IS NULL
            AND subject_user_id IS NULL
            AND tenancy_id IS NOT NULL
            AND agreement_version IS NOT NULL
            AND agreement_version > 0
        )
    ),

    CONSTRAINT resident_documents_ready_requires_verification CHECK (
        status <> 'ready'
        OR (
            verified_at IS NOT NULL
            AND verified_at >= created_at
            AND verified_content_type IS NOT NULL
            AND verified_content_type = declared_content_type
            AND verified_size_bytes IS NOT NULL
            AND verified_size_bytes = declared_size_bytes
            AND sha256 IS NOT NULL
        )
    ),

    CONSTRAINT resident_documents_rejection_reason CHECK (
        status <> 'rejected' OR failure_reason IS NOT NULL
    ),

    CONSTRAINT resident_documents_deletion_metadata CHECK (
        (status = 'deleted' AND deleted_at IS NOT NULL
            AND deleted_at >= created_at)
        OR (status <> 'deleted' AND deleted_at IS NULL)
    )
);

CREATE UNIQUE INDEX resident_documents_agreement_version_unique
    ON resident_documents(tenancy_id, agreement_version)
    WHERE kind = 'rental_agreement';

CREATE INDEX resident_documents_request_idx
    ON resident_documents(request_id, status)
    WHERE request_id IS NOT NULL;

CREATE INDEX resident_documents_subject_idx
    ON resident_documents(subject_user_id)
    WHERE subject_user_id IS NOT NULL;

CREATE INDEX resident_documents_uploader_idx
    ON resident_documents(uploaded_by);

CREATE INDEX resident_documents_pending_idx
    ON resident_documents(created_at)
    WHERE status = 'pending';


-- Record exactly which agreement the owner approved.
-- Replacing an agreement must not silently transfer that approval.
ALTER TABLE resident_unit_requests
    ADD COLUMN owner_reviewed_agreement_id UUID,

    ADD CONSTRAINT resident_requests_reviewed_agreement_fk
        FOREIGN KEY (
            owner_reviewed_agreement_id, society_id, tenancy_id
        )
        REFERENCES resident_documents(id, society_id, tenancy_id),

    ADD CONSTRAINT resident_requests_reviewed_agreement_consistent CHECK (
        (
            relationship = 'tenant'
            AND owner_review_status = 'approved'
            AND tenancy_id IS NOT NULL
            AND owner_reviewed_agreement_id IS NOT NULL
        )
        OR (
            owner_review_status <> 'approved'
            AND owner_reviewed_agreement_id IS NULL
        )
    );

CREATE INDEX resident_requests_reviewed_agreement_idx
    ON resident_unit_requests(owner_reviewed_agreement_id)
    WHERE owner_reviewed_agreement_id IS NOT NULL;


CREATE TABLE resident_document_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    society_id UUID NOT NULL REFERENCES societies(id),
    document_id UUID NOT NULL,
    actor_user_id UUID NOT NULL REFERENCES users(id),

    action TEXT NOT NULL CHECK (action IN (
        'upload_requested',
        'upload_verified',
        'upload_rejected',
        'access_granted',
        'deletion_requested',
        'deleted'
    )),

    -- Audit the authorisation basis, not just the portal name.
    access_basis TEXT NOT NULL CHECK (access_basis IN (
        'self',
        'verified_owner',
        'agreement_participant',
        'chairman_identity_review'
    )),

    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT resident_document_events_same_society_fk
        FOREIGN KEY (document_id, society_id)
        REFERENCES resident_documents(id, society_id)
);

CREATE INDEX resident_document_events_history_idx
    ON resident_document_events(document_id, created_at, id);

CREATE INDEX resident_document_events_actor_idx
    ON resident_document_events(actor_user_id, created_at);


-- Down Migration

DROP TABLE resident_document_events;

ALTER TABLE resident_unit_requests
    DROP CONSTRAINT resident_requests_reviewed_agreement_consistent,
    DROP CONSTRAINT resident_requests_reviewed_agreement_fk,
    DROP COLUMN owner_reviewed_agreement_id;

DROP TABLE resident_documents;

ALTER TABLE resident_unit_requests
    DROP CONSTRAINT resident_requests_applicant_identity_unique;
